import Head from 'next/head';


import styles from '@/styles/Home.module.css';

import AirportSelect from '@/components/AirportSelect/AirportSelect';
import { prisma } from '@/helpers/db';
import { Airport } from '@prisma/client';
import { AIRPORTS_TEST_DATA } from '@/components/AirportSelect/data';

export const getStaticProps = async () => {
  const airports = await prisma.airport.findMany();
  // const airports: Airport[] = [];

  return {
    props: {
      airports,
    },
  };
};

type HomeProps = {
  airports: Airport[];
};


export default function Home({ airports }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.Selector}>
          <AirportSelect
            name="origins"
            airports={airports.length ? airports : AIRPORTS_TEST_DATA }
            selectedAirports={[ airports[0], airports[1]]} 
            onChange={() => undefined}
          />
          <AirportSelect
            name="origins"
            airports={airports.length ? airports : AIRPORTS_TEST_DATA }
            selectedAirports={[ airports[74], airports[139]]} 
            onChange={() => undefined}
          />
        </div>
      </main>
    </>
  )
}
