import Head from "next/head";
import Link from "next/link";
import {useRouter} from "next/router";

import {TabsList} from "@/components/TabsList/TabsList";
import {Routes} from "@/app/routes";
import { SWRConfig } from "swr";

import styles from './MainLayout.module.scss';

type MainLayoutProps = {
  children: React.ReactNode;
}

const Links = [
  {href: Routes.ONE_WAY, label: 'One Way'},
  {href: Routes.RETURN, label: 'Return'},
  {href: Routes.MULTI_CITY, label: 'Multi City'},
  {href: Routes.EXPLORE, label: 'Explore'}
]

const swrConfig = {
  fetcher: (url: string) => fetch(url).then((res) => res.json()),
}

export default function MainLayout({children}: MainLayoutProps) {
  const router = useRouter();

  return (
    <SWRConfig value={swrConfig}>
      <Head>
        <title>N00mad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.MainLayout}>
        <header>
          <h1>N<span/><span/>mad</h1>
        </header>
        <main>
          <TabsList>
            {Links.map(({href, label}) => (
              <Link key={href} href={href} aria-selected={router.pathname === href}>
                {label}
              </Link>
            ))}
          </TabsList>
          <div className={styles.MainLayout__Content}>
            {children}
          </div>
        </main>
      </div>
    </SWRConfig>
  );
}