import {Fare} from "service/clients/ryanair/flights";
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {useEffect, useState} from "react";
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [data, setData] = useState([]);
  useEffect(() => {
    fetch('http://localhost:3000/api/allFares?origin=INI&fromDate=2022-07-01&toDate=2023-10-01')
      .then(async (res) => {
        const { data } = await res.json();
        setData(data);
      })
    return undefined;
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>
          01.07.2022. - 01.10.2022.
        </p>

        <div className={styles.grid}>
          {data.map((fareGroup: any) => (
            <div className={styles.card} key={fareGroup.origin + fareGroup.destination}>
              <h3>{fareGroup.origin} -> {fareGroup.destination}</h3>
              <table>
                <tbody>
                  {fareGroup.fares.map((fare: Fare) =>(
                    <tr key={fare.sellKey}>
                      <td>{fare.day}</td>
                      <td>{fare.price?.value} {fare.price?.currencySymbol}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ))}
        </div>
      </main>

    </div>
  )
}

export default Home
