name: Run airports.worker

on:
  workflow_dispatch:

jobs:
  run-workers:
    name: Airports Worker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install root dependencies
        run: npm install

      - name: Install service dependencies
        run: |
          cd service
          npm install

      - name: Run worker
        run: |
          cd service
          npm run airports.worker
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          WIZZAIR_API_URL: ${{ secrets.WIZZAIR_API_URL }}
