name: Run fares.workers

on:
  workflow_dispatch:

jobs:
  run-workers:
    name: Worker ${{ matrix.worker }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        worker: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        total: [10]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install root dependencies
        run: npm install

      - name: Install service dependencies
        run: |
          cd service
          npm install

      - name: Run worker
        run: |
          cd service
          npm run fares.worker -- ${{ matrix.worker }} ${{ matrix.total }}
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          WIZZAIR_API_URL: ${{ secrets.WIZZAIR_API_URL }}
